#!/bin/bash

# todo

optionsmenu() {
    echo ':b Delete all notification from application
:b Delete notifications containing keyword
:r 﫨Delete all notifications' | instantmenu -c -l 18 -h -1 -q 'notification options' -bw 4 -a 4
}
